name: Jira Remote Link
description: Creates remote links on Jira from GitHub issues

branding:
  icon: link
  color: green

inputs:
  jira-url:
    description: URL for Jira instance (i.e. `example.atlassian.net`)
    required: true

  jira-email:
    description: Email for Jira account (i.e. `john.doe@example.com`)
    required: true

  jira-token:
    description: Token for Jira account
    required: true

runs:
  using: composite
  steps:
    - id: action
      run: go run main.go -inputs '${{ toJSON(inputs) }}'
      working-directory: ${{ github.action_path }}
      shell: bash